### ISSUE TITLE
Viewing and navigating the background preview w/ DynaShape installed crashes Dynamo

### ISSUE THREAD

**Issue by dimven** [LongNguyenP/DynaShape_Legacy#1]
Hi,

Not sure if you've observer any similar behavior but a graph that was running fine before seems to crash whenever I enable the background preview and start navigating it. Here's a sample traceback from the crash:

> Object reference not set to an instance of an object.
> 
>    at DynaShape.DynaShapeViewExtension.ViewModelViewMouseMoveHandler(Object sender, MouseEventArgs e)
>    at Dynamo.Wpf.ViewModels.Watch3D.DefaultWatch3DViewModel.OnViewMouseMove(Object sender, MouseEventArgs e)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I don't have any DynaShape nodes currently placed on the graph and it's not a terribly heavy graph:
![revit_2017-11-21_16-43-34](https://user-images.githubusercontent.com/7148394/33062869-ac25b0c6-cedb-11e7-8f2b-d790662da2f1.png)

Any idea how I can avoid this without removing DynaShape?

**Comment by LongNguyenP** [comment]
Thanks for reporting the issue! I am aware that there is still some bugs relating to the viewport display. Will look into this as soon as I get some time during the Christmas holidays. Thanks for sharing the traceback, that's indeed very helpful.
